name: Deploy to EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-18-223-169-198.us-east-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/app"

  re-run:
    name: Re run the api on ec2
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Build the api
        run: docker build -t mwruth .
      - name: Stop running api
        run: docker rm -f mwruth
      - name: Run the api
        run: docker run -d -p 3000:3000 --name mwruth mwruth